version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: url-shortener:latest
    container_name: url-shortener
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - STORAGE_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-your_password}
      - DB_NAME=${DB_NAME:-urlshortener}
      - DB_SSLMODE=disable
    depends_on:
      - db
    networks:
      - url-shortener-network

  db:
    image: postgres:14-alpine
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-your_password}
      - POSTGRES_DB=${DB_NAME:-urlshortener}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local